# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5571b902b686ab08b05b4700066f1e209b3bd7bec39f463cb5b89e6c79ccd8614c9e52e12aa10c6b9325d588512844edd328e4494e821fe15561acd34c4cbc16

test:
  secret_key_base: 3116aaae17c1f1c48b529a9e62014941d448ca21d10f4f6a0d1c703b6a4d5afac102deda997ddac85095487ec524d54ff5b9208b2fe98c32e5c79001e612b6b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
